### ISSUE TITLE
Implement meta-parameters

### ISSUE THREAD

**Issue by a5kin** [a5kin/xentica#51]
We need meta-parameters with the ability to define them in the model, and their values settable per each experiment. It may seem like an easy task, but could result in the major refactoring of the base classes. The reasons are:
1. ``BSCA`` metaclass (where code generation occurs) and ``Experiment`` subclasses are not connected by any means. No way to use values from ``Experiment`` in the emit/absorb functions directly. The workaround is to use ``Constant`` mechanism, that will just generate a placeholder in ``#define`` and replace it by some value later, after the whole code is already generated. Yet, with ``Constant`` we can't provide dynamic code generation, i.e. optimization for 0 valued parameters.
2. ``Experiment`` is just a mockup right now, it doesn't provide any logic of the base class. What we need, is to check its attributes for sanity, to make sure they are corresponding to what the model awaits. Wrong types, wrong structures, missing attributes - all gonna be checked for good. And again, we can't do it right now, since the two base classes are not connected.
3. In not so distant future, we are planning that meta-params will integrate seamlessly with Moire. For that, we need to change ``MoireBridge`` dynamically, correspondingly to ``Experiment`` contents. At the current stage, we have to support this mechanism, to prevent us from another major refactoring later.

The goal for this issue is to replace constants in current EvoLife example with meta-params and make it run. Other things are really optional and probably be moved to separate issues.

TODO:
- [x] Move code generation to ``CellularAutomaton.__init__``
- [x] Rid off patterns replacing in ``Constant`` - they are unnecessary now
- [x] Implement ``MetaParameter`` class with default value and ``is_interactive`` flag (``True`` means the change of the parameter does not require code re-generation)
- [x] Populate ``meta`` attribute of the ``CellularAutomaton`` with the default values (in the ``BSCA`` metaclass)
- [x] ~~Change core constants (field size, zoom, etc.) to parameters~~ (separate issue #54 opened)
- [x] ~~Validate ``Experiment`` class~~ (unnecessary now)
- [x] Populate``meta`` values from the ``Experiment`` class

**Comment by a5kin** [comment]
Basic meta-parameters system have been implemented. So far, only non-interactive ones are available. This should be really enough to explore EvoLife parameter space and build all classic experiments. Interactive parameters will be implemented in future versions (issue #54). Right now, we will focus on EvoLife debugging, code coverage, docs, and 0.2 release preparations.
